"""
TradeFusion AI - Telegram Notifications
"""

import os
import requests
from typing import Optional, Dict


class TelegramNotifier:
    def __init__(self, token: Optional[str] = None, chat_id: Optional[str] = None):
        self.token = token or os.getenv("TELEGRAM_BOT_TOKEN")
        self.chat_id = chat_id or os.getenv("TELEGRAM_CHAT_ID")

    @property
    def is_configured(self) -> bool:
        return bool(self.token and self.chat_id)

    def send(self, message: str, parse_mode: str = "HTML") -> bool:
        if not self.is_configured:
            print("[Telegram] Not configured. Set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID.")
            return False

        url = f"https://api.telegram.org/bot{self.token}/sendMessage"
        payload = {
            "chat_id": self.chat_id,
            "text": message,
            "parse_mode": parse_mode,
            "disable_web_page_preview": True
        }
        try:
            r = requests.post(url, json=payload, timeout=10)
            return r.status_code == 200
        except Exception as e:
            print(f"[Telegram] Error: {e}")
            return False

    def send_signal(self, analysis: Dict) -> bool:
        signal = analysis.get("signal", "N/A")
        conf = analysis.get("confidence", 0)
        symbol = analysis.get("symbol", "ASSET")
        price = analysis.get("price", 0)
        risk = analysis.get("risk_mode", "medium").capitalize()
        structure = analysis.get("structure", {}).get("structure", "unknown").capitalize()

        emoji = "🟢" if signal == "BUY" else "🔴" if signal == "SELL" else "⚪"

        msg = (
            f"{emoji} <b>TRADEFUSION SIGNAL</b>\n\n"
            f"<b>Asset</b>: {symbol}\n"
            f"<b>Signal</b>: {signal}\n"
            f"<b>Confidence</b>: {conf}%\n"
            f"<b>Price</b>: {price}\n"
            f"<b>Risk Mode</b>: {risk}\n"
            f"<b>Structure</b>: {structure}\n"
        )

        if signal != "NO TRADE":
            msg += f"\n⏰ Generated by TradeFusion AI"

        return self.send(msg)
